Eng 217 local path
aixplain/aiXplain pull request #220
Opened 2024-08-08 16:09 UTC by thiago-aixplain

Treating dictionaries as content local paths as well (related to task https://aixplain.atlassian.net/browse/ENG-108)

```python
query = """You are a proposal writter for the given Request for Proposal (RFP) specialized in @specialization. It should formatted as a markdown file.
RFP: @rfp 
Improve the given proposal given the following guidelines. Guideline: @feedback
Proposal: @proposal
Output just the improved proposal and nothing else."""

content = {
    "@rfp": "rfp.txt",
    "@specialization": "specialization.txt",
    "@feedback": "feedback.txt",
    "@proposal": "proposal.txt",
}

agent = AgentFactory.get("...")
agent.run(query=query, content=content)
```

2024-08-08 20:10 UTC, tim-nelson commented
This is great! One consideration, what do you think about using Jinja syntax for Template variables? I.e. `{{variable_name}}`
(We also use Jinja syntax for variables in Design.)

```python
query = """You are a proposal writter for the given Request for Proposal (RFP) specialized in {{specialization}}. It should formatted as a markdown file.
RFP: {{rfp}}
Improve the given proposal given the following guidelines. Guideline: {{feedback}}
Proposal: {{proposal}}
Output just the improved proposal and nothing else."""

content = {
    "rfp": "rfp.txt",
    "specialization": "specialization.txt",
    "feedback": "feedback.txt",
    "proposal": "proposal.txt",
}

agent = AgentFactory.get("...")
agent.run(query=query, content=content)
```

2024-08-12 22:46 UTC, lucas-aixplain commented
> This is great! One consideration, what do you think about using Jinja syntax for Template variables? I.e. `{{variable_name}}` (We also use Jinja syntax for variables in Design.)
> 
> ```python
> query = """You are a proposal writter for the given Request for Proposal (RFP) specialized in {{specialization}}. It should formatted as a markdown file.
> RFP: {{rfp}}
> Improve the given proposal given the following guidelines. Guideline: {{feedback}}
> Proposal: {{proposal}}
> Output just the improved proposal and nothing else."""
> 
> content = {
>     "rfp": "rfp.txt",
>     "specialization": "specialization.txt",
>     "feedback": "feedback.txt",
>     "proposal": "proposal.txt",
> }
> 
> agent = AgentFactory.get("...")
> agent.run(query=query, content=content)
> ```

@thiago-aixplain, I agree with @tim-nelson that the depicted format using `{{variable_name}}` is cleaner to the user. That is also similar to what we're doing in Finetuner prompt template:
```python
prompt_template = """Given the context, generate the continuation:
Context: <<context>>
Continuation: <<continuation>>"""
```

2024-08-12 22:46 UTC, lucas-aixplain requested changes

2024-08-12 22:46 UTC, lucas-aixplain commented on aixplain/modules/agent/__init__.py
> +                assert len(content) <= 3, "The maximum number of content inputs is 3."
@tim-nelson, we need to set this max number of content in the documentation.

2024-08-13 17:50 UTC, lucas-aixplain approved these changes

2024-08-13 18:03 UTC, merged