Add AIXPLAIN_ENV environment variable
aixplain/aiXplain pull request #41
Opened 2023-06-02 20:26 UTC by lucas-aixplain

Instead of having to define `BACKEND_URL`, `MODELS_RUN_URL` and `PIPELINES_RUN_URL`, now we only need to define `AIXPLAIN_ENV` to set the desired environment (dev, test or platform).
Task: M-4576168247

2023-06-02 20:53 UTC, krishnadurai requested changes

2023-06-02 20:53 UTC, krishnadurai commented on aixplain/__init__.py
>  if config.TEAM_API_KEY == "" and config.AIXPLAIN_API_KEY == "":
@lucas-aixplain code cannot determine environment. This work is not compliant with the 12 factor app spec.

2023-06-13 12:10 UTC, lucas-aixplain commented
> Instead of having to define `BACKEND_URL`, `MODELS_RUN_URL` and `PIPELINES_RUN_URL`, now we only need to define `AIXPLAIN_ENV` to set the desired environment (dev, test or platform). Task: M-4576168247

Given the problems of creating an environment variable to determine the environment, this PR is updated only to remove PIPELINES_RUN_URL.

2023-06-13 14:52 UTC, krishnadurai approved these changes

2023-06-13 16:15 UTC, thiago-aixplain approved these changes

2023-06-20 12:36 UTC, krishnadurai commented
@lucas-aixplain what's the status of this unmerged PR?

2023-06-21 14:15 UTC, lucas-aixplain commented
@krishnadurai we can merge this PR, I think we didn't before because I was going to fix the unit tests first, but I'm working on other tasks for now.

2023-06-28 13:38 UTC, merged